#!/bin/sh

[ -z "$TZ" ] && export TZ="Asia/Seoul"

RUN_AT="${RUN_AT:-03:00}"

RUN_H=$(echo "$RUN_AT" | cut -d: -f1)
RUN_M=$(echo "$RUN_AT" | cut -d: -f2)

RUN_H=$((10#$RUN_H))
RUN_M=$((10#$RUN_M))
RUN_TARGET_SEC=$((RUN_H * 3600 + RUN_M * 60))

dump() {
  TS="$(date +%Y-%m-%dT%H:%M:%S)"
  ARCHIVE="/tmp/${TS}.archive.gz"
  S3_KEY="${TS}.archive.gz"

  echo "Starting MongoDB backup at $TS"


  echo "Running mongodump..."
  mongodump \
    --host="$DATABASE_HOST" \
    --username="$DATABASE_USER" \
    --port="$DATABASE_PORT" \
    --password="$DATABASE_PASSWORD" \
    --archive="$ARCHIVE" \
    --gzip

  echo "Uploading to S3..."
  aws s3 cp \
    "$ARCHIVE" \
    "s3://$S3_DUMP_URI/$S3_KEY" \
    --endpoint-url "$S3_ENDPOINT_URL"

  rm -f "$ARCHIVE"

  echo "Finished MongoDB backup: s3://$S3_DUMP_URI/$S3_KEY"
}

if [ "$1" = "now" ]; then
  echo "Wait 30 seconds for MongoDB bootstrap"
  sleep 30
  echo "Running immediate dump at $(date)"
  dump
  while :; do sleep 86400; done
fi

while :; do
  h=$(date +%H) || h=0
  m=$(date +%M) || m=0
  s=$(date +%S) || s=0

  h=$((10#$h))
  m=$((10#$m))
  s=$((10#$s))

  now_sec=$((h*3600 + m*60 + s))

  if [ "$now_sec" -lt "$RUN_TARGET_SEC" ]; then
    sleep_sec=$(( RUN_TARGET_SEC - now_sec ))
  else
    sleep_sec=$(( 24*3600 - now_sec + RUN_TARGET_SEC ))
  fi

  echo "Sleeping for $sleep_sec seconds until next $RUN_AT KST (now: $(date))"
  sleep "$sleep_sec"

  echo "Running scheduled dump at $(date)"
  dump
done
